apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "vault.fullname" . }}-vault-init
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: [""] 
  resources: ["serviceaccounts"]
  verbs: ["get", "watch", "list"]
  resourceNames:
    - {{ template "vault.fullname" . }}