{{- if .Values.global.vaultBootstrap }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "vault.fullname" . }}-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    #"helm.sh/hook-delete-policy": hook-succeeded
spec:
  selector: {}
  template:
    metadata:
      name: vault-init
    spec:
      serviceAccount: {{ template "vault.fullname" . }}
      containers:
        - name: vault-init
          image: {{ .Values.vaultBootstrap.image }}
          imagePullPolicy: Always
          command:
          - /app/vault-bootstrap
          env:
            - name: VAULT_ADDR
              value: https://{{ .Release.Name }}.{{ .Release.Namespace }}.svc:8200
            - name: VAULT_CLUSTER_MEMBERS
              value: {{ template "vault.nodes" . }}
            - name: VAULT_STORAGE_CLUSTER_MEMBERS
              value: {{ template "vault.storageNodes" . }}
            - name: VAULT_SERVICE_ACCOUNT
              value: {{ template "vault.fullname" . }}
            - name: VAULT_KEY_SHARES
              value: {{ .Values.vaultBootstrap.vaultKeyShares | quote }}
            - name: VAULT_KEY_THRESHOLD
              value: {{ .Values.vaultBootstrap.vaultKeyThreshold | quote }}
            - name: VAULT_ENABLE_INIT
              value: {{ .Values.vaultBootstrap.vaultInit | quote }}
            - name: VAULT_ENABLE_K8SSECRET
              value: {{ .Values.vaultBootstrap.vaultK8sSecret | quote }}
            - name: VAULT_ENABLE_UNSEAL
              value: {{ .Values.vaultBootstrap.vaultUnseal | quote }}
            - name: VAULT_ENABLE_K8SAUTH
              value: {{ .Values.vaultBootstrap.vaultK8sAuth | quote }}
      restartPolicy: Never
{{- end }}
